### ISSUE TITLE
A few things (0.14.2)

### ISSUE THREAD

**Issue by JCDcrafter** [BukkitPE/BukkitPE#33]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------
  First off I cannot place or break blocks for 0.14.2 would you be able to fix this?

I received an email you are going to be switching to java or something is there a download available yet? And since java uses .jar files is it possible we could just use Bukkit plugins straight onto BukkitPE? Or would they have to be ported?

Lastly I read a forum on someone asking how to port Bukkit plugins onto BukkitPE and got a reply to look in the plugin section and I can't see anything about porting plugins, is it possible to port them easily, if so how?

**Comment by xZeroMCPE** [comment]
For the 14.2 update there are some issues thats' causing some players to cannot place blocks Although, we will no longer provide support for BukkitPE (php) version since we are switching BukkitPE to java. And also when we are done switching BukkitPE to java. You may simple add bukkit plugins on the /plugins folder and BukkitPE will change what needs to be change such as things that MCPE does not support it will comment that line or just replace it with something else. But although we may just add a porting guide so you guys can port your own bukkits' plugins. :)

**Comment by JCDcrafter** [comment]
Oh BTW your staff are excellent! Always responding Good Work! And thanks for such an amazing version of Minecraft pe and I look forward to having java ☺

**Comment by xZeroMCPE** [comment]
@JCDcrafter  Thanks, remember to visit our site for better support! 

Forums.BukkitPE.net
